### ISSUE TITLE
missing the slash separating the database name

### ISSUE THREAD

**Issue by martinezmp3** [uhppoted/uhppoted-app-db#10]
request 
./uhppoted-app-db store-acl --dsn mysql://admin:password@tcp127.0.0.1:3306/mydatabase

Always return ERROR: invalid DSN: missing the slash separating the database name but the slash is there

**Comment by uhppoted** [comment]
Hi,

Not sure about the slash (it's a message from the MySQL driver) but that DSN looks like it's missing the brackets around the _host:port_. It may also need quotes because bash can be weird about an `@` in the command line. Try:
```
./uhppoted-app-db store-acl --dsn "mysql://admin:password@tcp(127.0.0.1:3306)/mydatabase"
```
BTW, tcp(127.0.0.1:3306) is the default DSN so you could probably just use:
```
./uhppoted-app-db store-acl --dsn "mysql://admin:password@/mydatabase"
```

It's described in the [README](https://github.com/uhppoted/uhppoted-app-db?tab=readme-ov-file#dsn) and in much more detail in the [driver README](https://github.com/go-sql-driver/mysql#dsn-data-source-name).

**Comment by uhppoted** [comment]
Closing, presuming fixed - feel free to reopen if you need to.
